/*
 * Copyright (c) 2016 Matthew Mikolay
 *
 * This file is part of Pocket CTC.
 *
 * Pocket CTC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Pocket CTC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Pocket CTC.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.mattmik.dianma;

import com.mattmik.dianma.tokenizer.CodepointTokenizer;
import com.mattmik.dianma.tokenizer.Tokenizer;

import org.junit.Test;

import java.util.NoSuchElementException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class CodepointTokenizerTest {

    @Test
    public void getInputTest() {

        Tokenizer tokenizer = new CodepointTokenizer("大家好！");
        assertEquals(tokenizer.getInput(), "大家好！");

    }

    @Test
    public void emptyStringHasMoreTokensTest() {

        Tokenizer tokenizer = new CodepointTokenizer("");
        assertFalse(tokenizer.hasMoreTokens());

    }

    @Test(expected = NoSuchElementException.class)
    public void emptyStringNextTokenTest() {

        new CodepointTokenizer("").nextToken();

    }

    @Test
    public void englishTokenizationTest() {

        Tokenizer tokenizer = new CodepointTokenizer("Lorem ipsum dolor sit amet, consectetur " +
                "adipiscing elit. Pellentesque ornare auctor bibendum. Phasellus pellentesque " +
                "nisl ut lectus porttitor, vitae euismod ex interdum. Donec mattis ornare " +
                "pulvinar. Sed mauris lacus, egestas eget porttitor ac, congue sed nulla. Proin " +
                "eget enim ut metus congue consectetur id sit amet elit. Cras consequat nibh et " +
                "hendrerit ornare. In sed ullamcorper orci, et cursus justo. Vestibulum arcu " +
                "nulla, porttitor id est vel, efficitur varius nulla. Nunc sed dolor " +
                "condimentum, consequat nisl a, tempor massa. In varius erat quis bibendum " +
                "pellentesque. Aenean sit amet malesuada odio.");

        assertTrue(tokenizer.hasMoreTokens());

        assertEquals((int) tokenizer.nextToken(), 76);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 80);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 80);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 120);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 68);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 83);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 80);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 67);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 73);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 106);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 86);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 102);
        assertEquals((int) tokenizer.nextToken(), 102);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 78);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 73);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 112);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 113);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 65);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 46);

        assertFalse(tokenizer.hasMoreTokens());

    }

    @Test
    public void chineseTokenizationTest() {

        Tokenizer tokenizer = new CodepointTokenizer("道者，令民與上同意也，可與之死，可與之生，" +
                "而不畏危。天者，陰陽，寒暑，時制也。地者，遠近，險易，廣狹，死生也。將者，智，信，仁，勇，" +
                "嚴也。法者，曲制，官道，主用也。凡此五者，將莫不聞，知之者勝，不知者不勝。");

        assertTrue(tokenizer.hasMoreTokens());

        assertEquals((int) tokenizer.nextToken(), 36947);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 20196);
        assertEquals((int) tokenizer.nextToken(), 27665);
        assertEquals((int) tokenizer.nextToken(), 33287);
        assertEquals((int) tokenizer.nextToken(), 19978);
        assertEquals((int) tokenizer.nextToken(), 21516);
        assertEquals((int) tokenizer.nextToken(), 24847);
        assertEquals((int) tokenizer.nextToken(), 20063);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 21487);
        assertEquals((int) tokenizer.nextToken(), 33287);
        assertEquals((int) tokenizer.nextToken(), 20043);
        assertEquals((int) tokenizer.nextToken(), 27515);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 21487);
        assertEquals((int) tokenizer.nextToken(), 33287);
        assertEquals((int) tokenizer.nextToken(), 20043);
        assertEquals((int) tokenizer.nextToken(), 29983);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 32780);
        assertEquals((int) tokenizer.nextToken(), 19981);
        assertEquals((int) tokenizer.nextToken(), 30031);
        assertEquals((int) tokenizer.nextToken(), 21361);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 22825);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 38512);
        assertEquals((int) tokenizer.nextToken(), 38525);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 23506);
        assertEquals((int) tokenizer.nextToken(), 26257);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 26178);
        assertEquals((int) tokenizer.nextToken(), 21046);
        assertEquals((int) tokenizer.nextToken(), 20063);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 22320);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 36960);
        assertEquals((int) tokenizer.nextToken(), 36817);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 38570);
        assertEquals((int) tokenizer.nextToken(), 26131);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 24291);
        assertEquals((int) tokenizer.nextToken(), 29433);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 27515);
        assertEquals((int) tokenizer.nextToken(), 29983);
        assertEquals((int) tokenizer.nextToken(), 20063);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 23559);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 26234);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 20449);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 20161);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 21191);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 22196);
        assertEquals((int) tokenizer.nextToken(), 20063);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 27861);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 26354);
        assertEquals((int) tokenizer.nextToken(), 21046);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 23448);
        assertEquals((int) tokenizer.nextToken(), 36947);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 20027);
        assertEquals((int) tokenizer.nextToken(), 29992);
        assertEquals((int) tokenizer.nextToken(), 20063);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 20961);
        assertEquals((int) tokenizer.nextToken(), 27492);
        assertEquals((int) tokenizer.nextToken(), 20116);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 23559);
        assertEquals((int) tokenizer.nextToken(), 33707);
        assertEquals((int) tokenizer.nextToken(), 19981);
        assertEquals((int) tokenizer.nextToken(), 32862);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 30693);
        assertEquals((int) tokenizer.nextToken(), 20043);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 21213);
        assertEquals((int) tokenizer.nextToken(), 65292);
        assertEquals((int) tokenizer.nextToken(), 19981);
        assertEquals((int) tokenizer.nextToken(), 30693);
        assertEquals((int) tokenizer.nextToken(), 32773);
        assertEquals((int) tokenizer.nextToken(), 19981);
        assertEquals((int) tokenizer.nextToken(), 21213);
        assertEquals((int) tokenizer.nextToken(), 12290);

        assertFalse(tokenizer.hasMoreTokens());

    }

    @Test
    public void whitespaceTokenizationTest() {

        Tokenizer tokenizer = new CodepointTokenizer(" \t \t\t   \n \n\n   \t       \t\n");

        assertTrue(tokenizer.hasMoreTokens());

        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 9);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 9);
        assertEquals((int) tokenizer.nextToken(), 9);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 10);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 10);
        assertEquals((int) tokenizer.nextToken(), 10);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 9);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 9);
        assertEquals((int) tokenizer.nextToken(), 10);

        assertFalse(tokenizer.hasMoreTokens());

    }

    @Test
    public void numberTokenizationTest() {

        Tokenizer tokenizer = new CodepointTokenizer("48367493264095895467254312390485094329089");

        assertTrue(tokenizer.hasMoreTokens());

        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 56);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 54);
        assertEquals((int) tokenizer.nextToken(), 55);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 54);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 48);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 53);
        assertEquals((int) tokenizer.nextToken(), 56);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 53);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 54);
        assertEquals((int) tokenizer.nextToken(), 55);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 53);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 49);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 48);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 56);
        assertEquals((int) tokenizer.nextToken(), 53);
        assertEquals((int) tokenizer.nextToken(), 48);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 57);
        assertEquals((int) tokenizer.nextToken(), 48);
        assertEquals((int) tokenizer.nextToken(), 56);
        assertEquals((int) tokenizer.nextToken(), 57);

        assertFalse(tokenizer.hasMoreTokens());

    }

    @Test
    public void mixedTokenizationTest() {

        Tokenizer tokenizer = new CodepointTokenizer("   To say \"hello\" in Chinese, you can " +
                "say 你好。 你会说英文吗？  今天是星期三。It is November 2, and there are 30 days in " +
                "this month. 42 is the meaning of life. 生活的意思是42。\t");

        assertTrue(tokenizer.hasMoreTokens());

        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 84);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 121);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 34);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 34);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 67);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 121);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 117);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 99);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 121);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 20320);
        assertEquals((int) tokenizer.nextToken(), 22909);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 20320);
        assertEquals((int) tokenizer.nextToken(), 20250);
        assertEquals((int) tokenizer.nextToken(), 35828);
        assertEquals((int) tokenizer.nextToken(), 33521);
        assertEquals((int) tokenizer.nextToken(), 25991);
        assertEquals((int) tokenizer.nextToken(), 21527);
        assertEquals((int) tokenizer.nextToken(), 65311);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 20170);
        assertEquals((int) tokenizer.nextToken(), 22825);
        assertEquals((int) tokenizer.nextToken(), 26159);
        assertEquals((int) tokenizer.nextToken(), 26143);
        assertEquals((int) tokenizer.nextToken(), 26399);
        assertEquals((int) tokenizer.nextToken(), 19977);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 73);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 78);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 118);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 98);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 44);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 114);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 51);
        assertEquals((int) tokenizer.nextToken(), 48);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 100);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 121);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 115);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 116);
        assertEquals((int) tokenizer.nextToken(), 104);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 109);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 97);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 110);
        assertEquals((int) tokenizer.nextToken(), 103);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 111);
        assertEquals((int) tokenizer.nextToken(), 102);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 108);
        assertEquals((int) tokenizer.nextToken(), 105);
        assertEquals((int) tokenizer.nextToken(), 102);
        assertEquals((int) tokenizer.nextToken(), 101);
        assertEquals((int) tokenizer.nextToken(), 46);
        assertEquals((int) tokenizer.nextToken(), 32);
        assertEquals((int) tokenizer.nextToken(), 29983);
        assertEquals((int) tokenizer.nextToken(), 27963);
        assertEquals((int) tokenizer.nextToken(), 30340);
        assertEquals((int) tokenizer.nextToken(), 24847);
        assertEquals((int) tokenizer.nextToken(), 24605);
        assertEquals((int) tokenizer.nextToken(), 26159);
        assertEquals((int) tokenizer.nextToken(), 52);
        assertEquals((int) tokenizer.nextToken(), 50);
        assertEquals((int) tokenizer.nextToken(), 12290);
        assertEquals((int) tokenizer.nextToken(), 9);

        assertFalse(tokenizer.hasMoreTokens());

    }

}
